repos:
-   repo: local
    hooks:
    - id: isort
      name: isort (python)
      entry: isort 
      args: ["--profile", "black", "."]
      language: python
      types: [python]
    # - id: pytest-check
    #   name: pytest-check
    #   entry: pytest
    #   language: system
    #   pass_filenames: false
    #   always_run: true
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
